name: agrartamfront CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
        - closed

  workflow_dispatch:

jobs:
  normal_deploy:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push') || (github.event.pull_request.merged == true) || (github.event_name == 'workflow_dispatch')
    steps:
      - name: frissit.sh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            ./agrarfrontfrissit.sh
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSHUSER }}
          privateKey: ${{ secrets.SSHKULCS }}
