name: agrartamfront CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
        - closed

  workflow_dispatch:

jobs:
  normal_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: frissit.sh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/code4.hu/agrartamfront
            ./frissit.sh
          host: ${{ secrets.HOST }}
          username: ubuntu
          privateKey: ${{ secrets.SSHKULCS }}

  pr_deploy:
      runs-on: ubuntu-latest
      if: github.event.pull_request.merged == true
      steps:
          - name: frissit.sh
            uses: garygrossgarten/github-action-ssh@release
            with:
                command: |
                    cd /var/www/code4.hu/agrartamfront
                    ./frissit.sh
                host: ${{ secrets.HOST }}
                username: ubuntu
                privateKey: ${{ secrets.SSHKULCS }}
